;             
CREATE USER IF NOT EXISTS SA SALT '1c0b944ad9b34258' HASH '59eb4c5f03ed072da041bf06af2f78da98bd7a361b8c24e4e46de668ee234bea' ADMIN;           
CREATE CACHED TABLE PUBLIC.T1(
    C1 DOUBLE NOT NULL,
    C2 DOUBLE NOT NULL,
    C3 VARCHAR(10),
    C4 INTEGER,
    C5 DOUBLE,
    C6 DOUBLE
);     
ALTER TABLE PUBLIC.T1 ADD CONSTRAINT PUBLIC.PK_T1_C1_C2 PRIMARY KEY(C1, C2);  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.T1;      
INSERT INTO PUBLIC.T1(C1, C2, C3, C4, C5, C6) VALUES
(1.0, 1.0, 'a', 1, 1.0, 1.0);           
CREATE CACHED TABLE PUBLIC.T2(
    C1 DOUBLE NOT NULL,
    C2 DOUBLE NOT NULL,
    C3 VARCHAR(10),
    C4 INTEGER,
    C5 DOUBLE,
    C6 DOUBLE
);     
ALTER TABLE PUBLIC.T2 ADD CONSTRAINT PUBLIC.PK_T2_C1_C2 PRIMARY KEY(C1, C2);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T2;      
CREATE CACHED TABLE PUBLIC.T3(
    C1 DOUBLE NOT NULL,
    C2 DOUBLE NOT NULL,
    C3 VARCHAR(10),
    C4 INTEGER,
    C5 DOUBLE,
    C6 DOUBLE
);     
ALTER TABLE PUBLIC.T3 ADD CONSTRAINT PUBLIC.PK_T3_C1_C2 PRIMARY KEY(C1, C2);  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.T3;      
INSERT INTO PUBLIC.T3(C1, C2, C3, C4, C5, C6) VALUES
(1.0, 1.0, 'a', 1, 1.0, 1.0);           
CREATE CACHED TABLE PUBLIC.T4(
    C1 DOUBLE NOT NULL,
    C2 DOUBLE NOT NULL,
    C3 VARCHAR(10),
    C4 INTEGER,
    C5 DOUBLE,
    C6 DOUBLE
);     
ALTER TABLE PUBLIC.T4 ADD CONSTRAINT PUBLIC.PK_T4_C1_C2 PRIMARY KEY(C1, C2);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T4;      
ALTER TABLE PUBLIC.T3 ADD CONSTRAINT PUBLIC.UK_T3_C3_C6 UNIQUE(C3, C6);       
ALTER TABLE PUBLIC.T1 ADD CONSTRAINT PUBLIC.UK_T1_C3_C4 UNIQUE(C3, C4);       
ALTER TABLE PUBLIC.T4 ADD CONSTRAINT PUBLIC.UK_T4_C4_C5 UNIQUE(C4, C5);       
ALTER TABLE PUBLIC.T2 ADD CONSTRAINT PUBLIC.UK_T2_C3_C5 UNIQUE(C3, C5);       
